name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create zip
        run: |
          mkdir -p dist
          git ls-files | zip -@ dist/chatgpt-speedup-${GITHUB_REF_NAME}.zip
      - name: Generate checksums
        run: |
          cd dist
          sha256sum *.zip > SHA256SUMS.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatgpt-speedup-${{ github.ref_name }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: chatgpt-speedup-${{ github.ref_name }}
          path: dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.zip
            dist/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
